spring:
  flyway:
    enabled: true
    locations: "classpath:db/migration"
    ignore-missing-migrations: true
    out-of-order: true
  datasource:
    url: jdbc:sqlserver://localhost:1433;database=db
    username: app_reproducer
    password: abcABC123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    hikari.connection-test-query: SELECT 1

camunda:
  bpm:
    admin-user:
      id: admin
      password: admin
    job-execution:
      enabled: true
    metrics:
      enabled: true
      db-reporter-activate: true
    default-serialization-format: application/json
    history-level: full
    generic-properties:
      properties:
        historyCleanupBatchWindowStartTime: 08:00+0000
        historyCleanupBatchWindowEndTime: 16:00+0000
        historyTimeToLive: P180D
        batchOperationHistoryTimeToLive: P180D
    database:
      schema-update: false

server:
  port: 8082
